spring:
  datasource:
    url: jdbc:oracle:thin:@132.130.150.34:1521/cinerdb
    username: bsgti
    password: lpsa2020
    hiraki:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.Oracle12cDialect
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
    com:
      pdr: TRACE
